[general]
import = ["~/.config/alacritty/tokyonight_night.toml"]

[font]
size = 14.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[window]
opacity = 0.95
padding = { x = 10, y = 10 }

[window.dimensions]
columns = 160
lines = 39

[cursor]
style = { shape = "Block", blinking = "Always" }

[selection]
save_to_clipboard = true
