# Animations for NORMAL windows.
{
    match = "window_type = 'normal' || window_type = 'dialog'";

    #=== Basic Preset ===#
    animations = (
        {
            triggers = ["close", "hide"];
            preset = "disappear";
            scale = 0.9;
            duration = 0.05;
        },
        {
            triggers = ["open", "show"];
            preset = "appear";
            scale = 0.9;
            duration = 0.15;
        }
    )
},

# Animations for Rofi launchers.
 {
    match = "class_g = 'Rofi'";
    animations = (
        {
         triggers = ["close", "hide"];
         preset = "disappear";
         duration = 0.01;
         scale = 0.5;
        },
        {
         triggers = ["open", "show"];
         preset = "appear";
         duration = 0.1;
         scale = 0.5;
        }
    )
 },

# Animations for Dunst notifications.
 {
      match = "class_g = 'Dunst'";
      animations = (
        {
           triggers = ["close", "hide"];
           preset = "fly-out"; #-dunst-close-preset
           direction = "up"; #-dunst-close-direction
           duration = 0.2;
        },
        {
           triggers = ["open", "show"];
           preset = "fly-in"; #-dunst-open-preset
           direction = "up"; #-dunst-open-direction
           duration = 0.2;
        }
      )
 },
