;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[global/wm]
include-file = $HOME/.config/polybar/catppuccin-mocha.ini

;== Gnome colors ==
; background = #1f1f1f
; background-alt = #2a2a2a
; foreground = #FFFFFF
; primary = #ffb300

[colors]
background=${colors.mantle}
background-alt = ${colors.crust}
foreground = ${colors.text}
primary = ${colors.mauve}
secondary = ${colors.blue}
alert = ${colors.red}
disabled = ${colors.overlay0}

[bar/main]
width = 100%
height = 22pt
radius = 0

fixed-center = true

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

border-bottom-size = 1pt
border-color=${colors.base}
# border-color= #282828

padding-left = 1
padding-right = 1

module-margin = 1
separator = |
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono Nerd Font:style=Medium:size=12;3"
font-1 = "JetBrainsMono Nerd Font:style=Medium:size=13;3"

modules-left = i3 xwindow
modules-center =
modules-right = systray pulseaudio date sysmenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 0pt
tray-spacing = 8pt

[module/workspaces]
type = internal/xworkspaces

label-active = 
label-active-foreground = ${colors.foreground}
label-active-padding = 1

label-occupied = 
label-occupied-padding = 1

label-empty = 
label-empty-background = ${colors.background}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label =   %class:0:20:...%
label-foreground = ${colors.foreground}

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = false
interval = 5
reverse-scroll = false

format-volume = <ramp-volume> <label-volume>

format-muted = <label-muted>
format-muted-prefix = 
format-muted-prefix-foreground = ${colors.alert}

label-volume = %percentage%%

label-muted = " muted"
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-foreground = ${colors.secondary}

click-right = pavucontrol &

[module/date]
type = internal/date
interval = 1

date = %H:%M%
date-alt = %a, %d %B %Y %H:%M

label = %date%
label-foreground = ${colors.foreground}

[module/sysmenu]
type = custom/text

format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-padding = 0

label = %{T2} %{T-}
click-right = xfce4-settings-manager &
click-left = ~/.config/rofi/powermenu/powermenu.sh &

[module/i3]
type = internal/i3

show-urgent = true

format = <label-state> <label-mode>

label-mode = %mode%
label-mode-padding = 2
label-mode-foreground = #000000
label-mode-background = ${colors.alert}

# label-focused = %{T2}%{T-}
label-focused = %index%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.secondary}
label-focused-padding = 1

label-unfocused = %index%
label-unfocused-padding = 1

label-urgent = %index%
label-urgent-foreground = ${colors.alert}
label-urgent-background = ${colors.base}
label-urgent-padding = 1

label-separator =
label-separator-padding = 0
label-separator-foreground = ${colors.disabled}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
