StylesPath = /home/anderson/.local/share/vale/styles

MinAlertLevel = suggestion

Packages = Google, proselint, write-good

[*]
# ^ This section applies to everting
#
# You can change (or add) file extensions here
# to apply these settings to other file types.
#
# For example, to apply these settings to both
# Markdown and reStructuredText:
#
# [*.{md,rst}]
BasedOnStyles = Vale, Google, proselint, write-good

# Desliga o corretor ortográfico nativo do Vale
Vale.Spelling = NO

# Desliga regras redundantes do write-good (Deixa o Google cuidar da voz passiva)
write-good.Passive = NO
write-good.TooWordy = NO
write-good.E-Prime = NO
