# Supported values
#  0: Default behaviour. Limits the frame rate to the selected display
#     refresh rate when vertical synchronization is enabled if the
#     actual display mode does not match the game's one.
#  n: Limit to n frames per second.
# -n: Limit to n frames per second if the game runs significantly faster
#     for a short period of time. This is primarily useful for app profiles,
#     as the limiter will not engage when running into Vsync or an external
#     limiter while running at more than n frames per second.
# -1: Always disables the limiter. This is a special value to deal with
#     games that default to a low refresh rate with no way to change it.

# dxgi.maxFrameRate = 60
# d3d9.maxFrameRate = 60
# dxvk.maxFrameRate = 60


# Overrides synchronization interval (Vsync) for presentation.
# Setting this to 0 disables vertical synchronization entirely.
# A positive value 'n' will enable Vsync and repeat the same
# image n times, and a negative value will have no effect.
#
# Supported values: Any non-negative number

dxgi.syncInterval = 2
d3d9.presentInterval = 2

